import { ProductDto } from "../products/dto/product.dto";
import { EntityRead } from "./entityRead";
export interface ProductReadDto extends ProductDto, EntityRead {}

export const products: ProductReadDto[] = [
    {
      id: 1,
      name: "Product 1",
      description: "Description 1",
      stock: 10,
      price: 19.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 2,
      name: "Product 2",
      description: "Description 2",
      stock: 1,
      price: 9.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 3,
      name: "Product 3",
      description: "Description 3",
      stock: 15,
      price: 39.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 4,
      name: "Product 4",
      description: "Description 4",
      stock: 5,
      price: 49.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 5,
      name: "Product 5",
      description: "Description 5",
      stock: 8,
      price: 59.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 6,
      name: "Product 6",
      description: "Description 6",
      stock: 12,
      price: 69.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 7,
      name: "Product 7",
      description: "Description 7",
      stock: 25,
      price: 79.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 8,
      name: "Product 8",
      description: "Description 8",
      stock: 30,
      price: 89.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 9,
      name: "Product 9",
      description: "Description 9",
      stock: 18,
      price: 99.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 10,
      name: "Product 10",
      description: "Description 10",
      stock: 22,
      price: 109.99,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    }, 
  ];