import { ProductDto } from "../products/dto/product.dto";

export const products: ProductDto[] = [
    {
      id: 1,
      name: "Alfajores",
      description: "Description 1",
      stock: 10,
      price: 19.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 2,
      name: "Auriculares inalámbricos",
      description: "Description 2",
      stock: 1,
      price: 9.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 3,
      name: "Aceite",
      description: "Description 3",
      stock: 15,
      price: 39.99,
      isActive: true,
        created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 4,
      name: "Cámara digital",
      description: "Description 4",
      stock: 5,
      price: 49.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 5,
      name: "Product 5",
      description: "Description 5",
      stock: 8,
      price: 59.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 6,
      name: "Product 6",
      description: "Description 6",
      stock: 12,
      price: 69.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 7,
      name: "Café",
      description: "Description 7",
      stock: 25,
      price: 79.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 8,
      name: "Leche",
      description: "Description 8",
      stock: 30,
      price: 89.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 9,
      name: "Arroz",
      description: "Description 9",
      stock: 18,
      price: 99.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    },
    {
      id: 10,
      name: "Lentejas",
      description: "Description 10",
      stock: 22,
      price: 109.99,
      isActive: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
    }, 
  ];